### ISSUE TITLE
Vue 3 / Vuex 4 support?

### ISSUE THREAD

**Issue by Grawl** [kadet1090/vuex-typings#2]
I see you have Vue 2 in `package.json`/`dependencies`

https://github.com/kadet1090/vuex-typings/blob/8c73e926e934193ab9de15b70b22f90c68792fed/package.json#L9

does it mean `vuex-typings` supports Vue 3 / Vuex 4?

**Comment by kadet1090** [comment]
This typings supports both, there are almost no differences between vuex 4 and 3 apart from store creation. The dependency is here only because I import `Watch` related types from vue - and this has not been changed. 

In fact, I am using this typings in one of my projects that I recently migrated from vue 2 to vue 3: https://github.com/cojedzie/cojedzie/blob/master/front/src/types/vuex.d.ts. And it worked almost without any changes - only thing I had to add was the `install` function of the store - I commited that change into this repo too. Also I changed the dependency to not be misleading :)
